# Generated by Django 4.2.1 on 2023-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstTeam', models.CharField(max_length=20)),
                ('firstTeamStatus', models.CharField(max_length=5)),
                ('goalsFirstTeam', models.IntegerField(default=0)),
                ('playersFirstTeam', models.CharField(max_length=300)),
                ('secondTeam', models.CharField(max_length=20)),
                ('secondTeamStatus', models.CharField(max_length=5)),
                ('goalsSecondTeam', models.IntegerField(default=0)),
                ('playersSecondTeam', models.CharField(max_length=300)),
                ('eventOwner', models.CharField(max_length=20)),
                ('eventStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=3)),
                ('teamName', models.CharField(max_length=20)),
                ('win', models.CharField(max_length=3)),
                ('loss', models.CharField(max_length=3)),
                ('draw', models.CharField(max_length=3)),
            ],
        ),
    ]
